// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import BtnController from "./btn_controller"
application.register("hello", BtnController)

import MapController from "./map_controller"
application.register("map", MapController)

// import FacebookController from "./facebook_controller"
// application.register("facebook", FacebookController)
